### ISSUE TITLE
ERROR: 04-chatgpt-local - WebGPU

### ISSUE THREAD

**Issue by JJozef** [midudev/javascript-100-proyectos#40]
Me dio este error al intentar probar el proyecto.

![Captura desde 2024-06-12 15-38-33](https://github.com/midudev/javascript-100-proyectos/assets/101532359/318078d4-8865-4b62-9ff4-8c4b72eed8ed)

- Brave 
     - Versión 1.66.118 
     - Chromium: 125
- Ubuntu 24.04 LTS
- GPU: GTX 1650 SUPER
- CPU: Ryzen 5 3500x

**Comment by jorgrim** [comment]
Yo resolví el problema activando la aceleración de gráficos: 

chrome://settings/system

y pinchar en "Usar la aceleración de gráficos cuando esté disponible"
